export type ShellSnippetType = "export" | "alias" | "snippet";

export interface ShellSnippet {
  id: string;
  name: string;
  type: ShellSnippetType;
  content: string;
  enabled: boolean;
  description?: string;
}

export interface ShellConfig {
  version: 1;
  snippets: ShellSnippet[];
}

export function createEmptyShellConfig(): ShellConfig {
  return {
    version: 1,
    snippets: [],
  };
}

export function parseShellConfig(jsonStr: string): ShellConfig {
  if (!jsonStr || jsonStr.trim() === "") return createEmptyShellConfig();
  try {
    const data = JSON.parse(jsonStr);
    if (!data || typeof data !== "object") return createEmptyShellConfig();
    return {
      version: 1,
      snippets: Array.isArray(data.snippets) ? data.snippets : [],
    };
  } catch {
    return createEmptyShellConfig();
  }
}

export function formatShellConfig(config: ShellConfig): string {
  return JSON.stringify(config, null, 2) + "\n";
}

export function addShellSnippet(
  config: ShellConfig,
  snippet: Omit<ShellSnippet, "id">
): { config: ShellConfig; snippet: ShellSnippet } {
  const id = `sh_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const newSnippet: ShellSnippet = {
    ...snippet,
    id,
  };
  return {
    config: {
      ...config,
      snippets: [...config.snippets, newSnippet],
    },
    snippet: newSnippet,
  };
}

export function updateShellSnippet(
  config: ShellConfig,
  id: string,
  updates: Partial<Omit<ShellSnippet, "id">>
): ShellConfig {
  return {
    ...config,
    snippets: config.snippets.map((s) => (s.id === id ? { ...s, ...updates } : s)),
  };
}

export function removeShellSnippet(config: ShellConfig, id: string): ShellConfig {
  return {
    ...config,
    snippets: config.snippets.filter((s) => s.id !== id),
  };
}

export function toggleShellSnippet(config: ShellConfig, id: string): ShellConfig {
  return {
    ...config,
    snippets: config.snippets.map((s) => (s.id === id ? { ...s, enabled: !s.enabled } : s)),
  };
}

/**
 * 粗略判断片段内容是否符合它声明的类型:export 类型建议以 export 开头,
 * alias 类型建议以 alias 开头(跳过内容开头的空行/注释行再判断,允许有变体写法如 `alias -g`)。
 * snippet(自定义脚本)类型不做任何限制,内容为空或只有注释时也不判定。
 *
 * 注意:这只是给用户一个温和提示用的启发式判断,不是强校验——
 * 类型字段本身只影响 UI 分组与生成文件时的注释头,不限制实际可写的内容。
 */
export function matchesDeclaredType(type: ShellSnippetType, content: string): boolean {
  if (type === "snippet") return true;

  const firstMeaningfulLine = content
    .split("\n")
    .map((l) => l.trim())
    .find((l) => l !== "" && !l.startsWith("#"));

  if (!firstMeaningfulLine) return true;

  if (type === "export") return /^export\b/i.test(firstMeaningfulLine);
  if (type === "alias") return /^alias\b/i.test(firstMeaningfulLine);
  return true;
}

/**
 * 将启用的片段编译为 ~/.env-butler/shell.sh
 */
export function generateShellScript(snippets: ShellSnippet[]): string {
  const activeSnippets = snippets.filter((s) => s.enabled && s.content.trim() !== "");

  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# ============================================================================",
    "# Generated by Env Butler. DO NOT EDIT THIS FILE DIRECTLY.",
    "# To use this file, add the following line to your ~/.zshrc or ~/.bashrc:",
    "#   source ~/.env-butler/shell.sh",
    "# ============================================================================",
    "",
  ];

  for (const item of activeSnippets) {
    const desc = item.description ? ` - ${item.description}` : "";
    lines.push(`# [${item.type.toUpperCase()}] ${item.name}${desc}`);
    lines.push(item.content.trim());
    lines.push("");
  }

  return lines.join("\n");
}
