import { parseVersionedConfig } from "./configFile.js";

export type ShellSnippetType = "export" | "alias" | "snippet";

export interface ShellSnippet {
  id: string;
  name: string;
  type: ShellSnippetType;
  content: string;
  enabled: boolean;
  description?: string;
}

export interface ShellConfig {
  version: 1;
  snippets: ShellSnippet[];
}

export function createEmptyShellConfig(): ShellConfig {
  return {
    version: 1,
    snippets: [],
  };
}

/** 当前扩展写出的 Shell 配置版本。改结构时 +1,并在 migrateShellConfig 里补一段迁移 */
export const CURRENT_SHELL_CONFIG_VERSION = 1;

/**
 * 解析 Shell 配置。空内容 → 空配置;损坏或版本过新 → 抛 ConfigFileError。
 * 这里静默返回空的危害比注册表更大:保存时会连带重新生成 shell.sh,
 * 等于把用户的全局环境变量和 alias 一起清空。
 */
export function parseShellConfig(jsonStr: string): ShellConfig {
  const parsed = parseVersionedConfig(jsonStr, CURRENT_SHELL_CONFIG_VERSION);
  if (!parsed) return createEmptyShellConfig();

  return migrateShellConfig(
    {
      version: CURRENT_SHELL_CONFIG_VERSION,
      snippets: Array.isArray(parsed.data.snippets) ? (parsed.data.snippets as ShellSnippet[]) : [],
    },
    parsed.version
  );
}

/** 老版本数据升级到当前版本。目前只有 v1,留接缝同 migrateRegistry */
export function migrateShellConfig(config: ShellConfig, fromVersion: number): ShellConfig {
  if (fromVersion === CURRENT_SHELL_CONFIG_VERSION) return config;
  return config;
}

export function formatShellConfig(config: ShellConfig): string {
  return JSON.stringify(config, null, 2) + "\n";
}

export function addShellSnippet(
  config: ShellConfig,
  snippet: Omit<ShellSnippet, "id">
): { config: ShellConfig; snippet: ShellSnippet } {
  const id = `sh_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const newSnippet: ShellSnippet = {
    ...snippet,
    id,
  };
  return {
    config: {
      ...config,
      snippets: [...config.snippets, newSnippet],
    },
    snippet: newSnippet,
  };
}

export function updateShellSnippet(
  config: ShellConfig,
  id: string,
  updates: Partial<Omit<ShellSnippet, "id">>
): ShellConfig {
  return {
    ...config,
    snippets: config.snippets.map((s) => (s.id === id ? { ...s, ...updates } : s)),
  };
}

export function removeShellSnippet(config: ShellConfig, id: string): ShellConfig {
  return {
    ...config,
    snippets: config.snippets.filter((s) => s.id !== id),
  };
}

export function toggleShellSnippet(config: ShellConfig, id: string): ShellConfig {
  return {
    ...config,
    snippets: config.snippets.map((s) => (s.id === id ? { ...s, enabled: !s.enabled } : s)),
  };
}

/**
 * 粗略判断片段内容是否符合它声明的类型:export 类型建议以 export 开头,
 * alias 类型建议以 alias 开头(跳过内容开头的空行/注释行再判断,允许有变体写法如 `alias -g`)。
 * snippet(自定义脚本)类型不做任何限制,内容为空或只有注释时也不判定。
 *
 * 注意:这只是给用户一个温和提示用的启发式判断,不是强校验——
 * 类型字段本身只影响 UI 分组与生成文件时的注释头,不限制实际可写的内容。
 */
export function matchesDeclaredType(type: ShellSnippetType, content: string): boolean {
  if (type === "snippet") return true;

  const firstMeaningfulLine = content
    .split("\n")
    .map((l) => l.trim())
    .find((l) => l !== "" && !l.startsWith("#"));

  if (!firstMeaningfulLine) return true;

  if (type === "export") return /^export\b/i.test(firstMeaningfulLine);
  if (type === "alias") return /^alias\b/i.test(firstMeaningfulLine);
  return true;
}

/**
 * 将启用的片段编译为 ~/.env-butler/shell.sh
 */
/**
 * 把片段在生成顺序里上移/下移一位。
 *
 * 顺序不是审美问题:generateShellScript 按数组顺序平铺输出,shell 从上往下执行,
 * 所以后面的片段能用到前面片段定义的东西,反过来不行。典型例子:
 *   export JAVA_HOME=/opt/jdk17
 *   export PATH="$JAVA_HOME/bin:$PATH"   ← 必须排在上面那条之后,否则 $JAVA_HOME 展开为空
 * 而且这种错不会报错,只会让命令莫名其妙找不到,所以要给用户调顺序的手段。
 *
 * 已经在最前/最后时原样返回配置,由调用方决定要不要提示。
 */
export function moveShellSnippet(config: ShellConfig, id: string, direction: "up" | "down"): ShellConfig {
  const index = config.snippets.findIndex((s) => s.id === id);
  if (index < 0) return config;

  const targetIndex = direction === "up" ? index - 1 : index + 1;
  if (targetIndex < 0 || targetIndex >= config.snippets.length) return config;

  const snippets = [...config.snippets];
  const moved = snippets[index];
  const displaced = snippets[targetIndex];
  if (!moved || !displaced) return config;

  snippets[index] = displaced;
  snippets[targetIndex] = moved;
  return { ...config, snippets };
}

export function generateShellScript(snippets: ShellSnippet[]): string {
  const activeSnippets = snippets.filter((s) => s.enabled && s.content.trim() !== "");

  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# ============================================================================",
    "# Generated by Env Butler. DO NOT EDIT THIS FILE DIRECTLY.",
    "# To use this file, add the following line to your ~/.zshrc or ~/.bashrc:",
    "#   source ~/.env-butler/shell.sh",
    "# ============================================================================",
    "",
  ];

  for (const item of activeSnippets) {
    const desc = item.description ? ` - ${item.description}` : "";
    lines.push(`# [${item.type.toUpperCase()}] ${item.name}${desc}`);
    lines.push(item.content.trim());
    lines.push("");
  }

  return lines.join("\n");
}
